In [64]:
import numpy as np  

In [65]:
class CNN():

    def __init__(self,Image_channel:np.ndarray, filter: np.ndarray,Pooling_size=2, mode="max", stride: int = 1):
        self.Image_channel = Image_channel
        self.filter =filter
        self.Pooling_size =Pooling_size
        self.mode =mode
        self.stride = stride
        

        self.Filerting = self.__CNN_func(self.Image_channel,self.filter,self.stride)
        

    
    def __CNN_func(self,input: np.ndarray, filter: np.ndarray, stride: int = 1):
        input_size = input.shape[0]
        filter_size = filter.shape[0]
        output_size = int(((input_size - filter_size) / stride) + 1)
        output = np.zeros((output_size, output_size))
        
        for i in range(0, output_size * stride, stride):
            for j in range(0, output_size * stride, stride):
                region = input[i:i+filter_size, j:j+filter_size]
                output[i // stride, j // stride] = np.sum(region * filter, dtype=np.int16)
                
                sum_values = []
                for row in range(filter_size):
                    for col in range(filter_size):
                        sum_values.append(f"({region[row, col]} x {filter[row, col]})")
        return output
    
    def get_value(self):
        return self.Filerting
        




In [66]:
R = np.array([
    [112, 125,  25,  80, 220, 110],
    [150,  95,  15, 100, 115, 152],
    [200, 100,  48,  90,  70, 175],
    [187,  56,  43,  86, 180, 200],
    [190,  87,  70,  37,  24,  35],
    [ 80,  75,  65,  45,  32,  20]
])

R = np.pad(R, pad_width=1, mode='constant', constant_values=0)

filter_1 = np.array([
    [ 1,  1,  1,  0],
    [ 0,  1,  1,  1,],
    [-1,  0,  0,  1,],
    [-1,  0,  1, -1],
    
])

red_filter = CNN(R,filter_1,stride=2)

print("After convolution =")
print(matrix:=red_filter.get_value(),"\n")


pooled_matrix = np.array([
    [np.max(matrix[:2, :2]), np.max(matrix[:2, 2:])],
    [np.max(matrix[1:, :2]), np.max(matrix[1:, 2:])]])


print("After Max Poolin =")
print(pooled_matrix)






After convolution =
[[329. 265. 315.]
 [653. 468. 524.]
 [655. 273. 480.]] 

After Max Poolin =
[[653. 524.]
 [655. 524.]]


In [67]:
G = np.array([
    [150, 125,  38,  80,  20,  10],
    [130,  95,  25, 100, 115, 152],
    [ 80, 100, 148,  90,  70, 175],
    [170, 160,  43, 160, 170, 180],
    [100, 150,  70,  37, 124, 135],
    [ 85,  75,  65,  45, 232, 120]
])

G = np.pad(G, pad_width=1, mode='constant', constant_values=0)


filter_2 = np.array([
    [ 0, -1, -1, 0],
    [ 1, -1, 1, -1],
    [ 1,  0,  0,  1,],
    [ 1,  0,  1, 1],
])

red_filter = CNN(G,filter_2,stride=2)
print("After convolution =")
print(matrix:=red_filter.get_value(),"\n")
np.max(matrix)

pooled_matrix = np.array([
    [np.max(matrix[:2, :2]), np.max(matrix[:2, 2:])],
    [np.max(matrix[1:, :2]), np.max(matrix[1:, 2:])]
])
print("After Max Poolin =")

print(pooled_matrix)



After convolution =
[[ 210.  617.  435.]
 [ -90.  488.  260.]
 [-285.   97. -257.]] 

After Max Poolin =
[[617. 435.]
 [488. 260.]]


In [68]:
B = np.array([
    [200, 125,  25,  80, 220, 150],
    [ 50,  95,  15, 150, 115, 152],
    [ 90, 110,  48, 190,  70, 175],
    [180, 135,  43, 106, 180, 110],
    [ 55,  98,  70,  37,  24,  35],
    [ 78, 150,  65,  45,  32,  80]
])
B = np.pad(B, pad_width=1, mode='constant', constant_values=0)

filter_3 = np.array([
    [ 1,  1,  1,  0],
    [-1,  1,  1,  1,],
    [0,  1,  0,  1,],
    [-1, -1,  1,  1,]
])

red_filter = CNN(B,filter_3,stride=2)
print("After convolution =")
print(matrix:=red_filter.get_value(),"\n")



pooled_matrix = np.array([
    [np.max(matrix[:2, :2]), np.max(matrix[:2, 2:])],
    [np.max(matrix[1:, :2]), np.max(matrix[1:, 2:])]
])
print("After Max Poolin =")
print(pooled_matrix)





After convolution =
[[483. 432. 320.]
 [729. 574. 626.]
 [681. 414. 450.]] 

After Max Poolin =
[[729. 626.]
 [729. 626.]]
