In [11]:
import numpy as np


def CNN(input:np.ndarray,filter:np.ndarray):
    input_size = input.shape[0]
    filter_size = filter.shape[0]
    output_size = int((input_size - filter_size) + 1)
    output = np.zeros((output_size,output_size))  
    for i in range(output_size): 
        for j in range(output_size):  
            region = input[i:i+3, j:j+3]
            output[i, j] = np.sum(region * filter,dtype=np.int16)
    return output

Red Channel Matrix

In [12]:
matrix_R = np.array([
    [0,0,0,0,0,0],
    [0,156,155,156,158,158],
    [0,153,154,157,159,159],
    [0,149,151,155,158,159],
    [0,146,146,149,153,158],
    [0,145,143,143,148,158]])


filter_R = np.array([
    [-1,-1,1],
    [0,1,-1],
    [0,1,1]])


output_R = CNN(matrix_R,filter_R)
print(output_R)


[[308. 310. 314. 318.]
 [298. 148. 158. 161.]
 [291. 141. 147. 153.]
 [290. 138. 139. 147.]]


Green Channel Matrix

In [13]:
matrix_G = np.array([
    [0,0,0,0,0,0],
    [0,167,166,167,169,169],
    [0,164,165,168,170,170],
    [0,160,162,166,169,170],
    [0,156,156,159,163,168],
    [0,155,153,153,158,168]
])


filter_G = np.array([
    [1,0,0],
    [1,-1,-1],
    [1,0,-1]   
    ])


output_G = CNN(matrix_G,filter_G)
print(output_G)


[[-498. -170. -175. -173.]
 [-491.   -8.  -14.   -9.]
 [-478.   -7.  -15.  -14.]
 [-465.    3.   -9.  -21.]]


Blue Channel Matrix

In [14]:
matrix_B = np.array([
    [0,0,0,0,0,0],
    [0,163,162,163,165,165],
    [0,160,161,164,166,166],
    [0,156,158,162,165,166],
    [0,155,155,158,162,167],
    [0,154,152,152,157,167]
])


filter_B = np.array([
    [0,1,1],
    [0,1,0],
    [1,-1,1]   
    ])


output_B = CNN(matrix_B,filter_B)
print(output_B)





[[164. 325. 326. 329.]
 [487. 646. 653. 659.]
 [477. 641. 651. 660.]
 [467. 629. 642. 655.]]


The Final Result 

In [15]:
values = []
for row in range(output_B.shape[0]):
    for column in range(output_B.shape[0]):
        values.append(output_R[row][column] + output_G[row][column] +output_B[row][column] + 1)
result = np.array((values),dtype=np.int16).reshape(4,4)

print(result)

[[-25 466 466 475]
 [295 787 798 812]
 [291 776 784 800]
 [293 771 773 782]]
